-- MySQL Script generated by MySQL Workbench
-- Mon Dec  2 11:00:16 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema ArtGallery
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ArtGallery
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ArtGallery` ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`artist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`artist` (
  `artist_id` VARCHAR(16) NOT NULL);


-- -----------------------------------------------------
-- Table `mydb`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genre` (
  ``  NOT NULL);


-- -----------------------------------------------------
-- Table `mydb`.`movement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`movement` (
  ``  NOT NULL);


-- -----------------------------------------------------
-- Table `mydb`.`recommendations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recommendations` (
  ``  NOT NULL);


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  ``  NOT NULL);


-- -----------------------------------------------------
-- Table `mydb`.`favorite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`favorite` (
  ``  NOT NULL);

USE `ArtGallery` ;

-- -----------------------------------------------------
-- Table `ArtGallery`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ArtGallery`.`Users` (
  `user_id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX (`email` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `ArtGallery`.`ArtMovements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ArtGallery`.`ArtMovements` (
  `movement_id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`movement_id`),
  UNIQUE INDEX (`name` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `ArtGallery`.`Genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ArtGallery`.`Genres` (
  `genre_id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`genre_id`),
  UNIQUE INDEX (`name` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `ArtGallery`.`Artists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ArtGallery`.`Artists` (
  `artist_id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `date_of_birth` INT NOT NULL,
  `date_of_death` INT NULL DEFAULT NULL,
  `place_of_birth` TEXT NOT NULL,
  `movement_id` INT NULL DEFAULT NULL,
  `genre_id` INT NULL DEFAULT NULL,
  `bio` TEXT NOT NULL,
  PRIMARY KEY (`artist_id`),
  INDEX (`movement_id` ASC) VISIBLE,
  INDEX (`genre_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`movement_id`)
    REFERENCES `ArtGallery`.`ArtMovements` (`movement_id`),
  CONSTRAINT ``
    FOREIGN KEY (`genre_id`)
    REFERENCES `ArtGallery`.`Genres` (`genre_id`));


-- -----------------------------------------------------
-- Table `ArtGallery`.`Paintings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ArtGallery`.`Paintings` (
  `painting_id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `artist_id` INT NOT NULL,
  `style_id` INT NULL DEFAULT NULL,
  `genre_id` INT NULL DEFAULT NULL,
  `year` INT NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`painting_id`),
  INDEX (`artist_id` ASC) VISIBLE,
  INDEX (`style_id` ASC) VISIBLE,
  INDEX (`genre_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`artist_id`)
    REFERENCES `ArtGallery`.`Artists` (`artist_id`),
  CONSTRAINT ``
    FOREIGN KEY (`style_id`)
    REFERENCES `ArtGallery`.`ArtMovements` (`movement_id`),
  CONSTRAINT ``
    FOREIGN KEY (`genre_id`)
    REFERENCES `ArtGallery`.`Genres` (`genre_id`));


-- -----------------------------------------------------
-- Table `ArtGallery`.`Favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ArtGallery`.`Favorites` (
  `user_id` INT NOT NULL,
  `painting_id` INT NOT NULL,
  `added_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`, `painting_id`),
  INDEX (`painting_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`user_id`)
    REFERENCES `ArtGallery`.`Users` (`user_id`),
  CONSTRAINT ``
    FOREIGN KEY (`painting_id`)
    REFERENCES `ArtGallery`.`Paintings` (`painting_id`));


-- -----------------------------------------------------
-- Table `ArtGallery`.`Tests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ArtGallery`.`Tests` (
  `test_id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `difficulty` INT NULL DEFAULT 'medium',
  `artist_id` INT NULL,
  PRIMARY KEY (`test_id`),
  INDEX `artsit_id_idx` (`artist_id` ASC) VISIBLE,
  CONSTRAINT `artsit_id`
    FOREIGN KEY (`artist_id`)
    REFERENCES `ArtGallery`.`Artists` (`artist_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ArtGallery`.`Questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ArtGallery`.`Questions` (
  `question_id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `test_id` INT NOT NULL,
  `question_text` TEXT NOT NULL,
  PRIMARY KEY (`question_id`),
  INDEX (`test_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`test_id`)
    REFERENCES `ArtGallery`.`Tests` (`test_id`));


-- -----------------------------------------------------
-- Table `ArtGallery`.`Answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ArtGallery`.`Answers` (
  `answer_id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `question_id` INT NOT NULL,
  `answer_text` VARCHAR(255) NOT NULL,
  `is_correct` TINYINT NULL DEFAULT FALSE,
  PRIMARY KEY (`answer_id`),
  INDEX (`question_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`question_id`)
    REFERENCES `ArtGallery`.`Questions` (`question_id`));


-- -----------------------------------------------------
-- Table `ArtGallery`.`UserTestResults`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ArtGallery`.`UserTestResults` (
  `result_id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `test_id` INT NOT NULL,
  `score` INT NOT NULL,
  `completion_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`result_id`),
  INDEX (`user_id` ASC) VISIBLE,
  INDEX (`test_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`user_id`)
    REFERENCES `ArtGallery`.`Users` (`user_id`),
  CONSTRAINT ``
    FOREIGN KEY (`test_id`)
    REFERENCES `ArtGallery`.`Tests` (`test_id`));


-- -----------------------------------------------------
-- Table `ArtGallery`.`Answers_copy1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ArtGallery`.`Answers_copy1` (
  `answer_id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `question_id` INT NOT NULL,
  `answer_text` VARCHAR(255) NOT NULL,
  `is_correct` TINYINT NULL DEFAULT FALSE,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`answer_id`),
  INDEX (`question_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`question_id`)
    REFERENCES `ArtGallery`.`Questions` (`question_id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
